import pandas as pd
from datetime import datetime


# get the model data in a DataFrame
datafile = 'Climate_stresses_update_1947_2018.dat'
cols = ['year', 'month', 'day', 'hour', 'min', 'sec', 'precip01', 'precip02', 'tmax01', 'tmax02', 'tmin01', 'tmin02']
df_srphm_data = pd.read_table(datafile, skiprows=5, names=cols, delim_whitespace=True)
df_srphm_data['date'] = pd.to_datetime(df_srphm_data[['year', 'month', 'day']])
enddate = df_srphm_data['date'].max()
df_future = pd.read_csv('gcm_srphm_future_corrected.csv', header=0, parse_dates=['date'])
df_future = df_future.loc[df_future['date'] > enddate]
df_future['year'] = pd.DatetimeIndex(df_future['date']).year
df_future['month'] = pd.DatetimeIndex(df_future['date']).month
df_future['day'] = pd.DatetimeIndex(df_future['date']).day
cols = ['date', 'precip01', 'precip02', 'tmax01', 'tmax02', 'tmin01', 'tmin02']
modlist = ['CanESM2', 'CNRM-CM5', 'HadGEM2-ES', 'MIROC5']
scenlist = ['rcp45', 'rcp85']
newlin = '\n'

for mod in modlist:
        for scen in scenlist:
                # open the new data file for this model/scenario
                outfile = open('{}_{}_srphm_corrected_future.data'.format(mod, scen), 'w')
                outfile.write('generated by build_data_file.py appended to original '
                              'file Climate_stresses_update_1947_2018.dat{}'.format(newlin))
                outfile.write('precip 2{}'.format(newlin))
                outfile.write('tmax 2{}'.format(newlin))
                outfile.write('tmin 2{}'.format(newlin))
                outfile.write('###################{}'.format(newlin))
                pr01 = 'pr_day_{}_{}_ap_cor'.format(mod, scen)
                pr02 = 'pr_day_{}_{}_sr_cor'.format(mod, scen)
                tmax01 = 'tasmax_day_{}_{}_ap_cor'.format(mod, scen)
                tmax02 = 'tasmax_day_{}_{}_sr_cor'.format(mod, scen)
                tmin01 = 'tasmin_day_{}_{}_ap_cor'.format(mod, scen)
                tmin02 = 'tasmin_day_{}_{}_sr_cor'.format(mod, scen)
                for index, row in df_srphm_data.iterrows():
                        line = '{} {:>3} {:>3}  0 0 0  {:>5.4f}  {:>5.4f}'.format(row['year'], row['month'], row['day'],
                                                                                  row['precip01'], row['precip02'])
                        line += '  {:>8.4f}  {:>8.4f}  {:>8.4f}  {:>8.4f}{}'.format(row['tmax01'], row['tmax02'],
                                                                                    row['tmin01'], row['tmin02'],
                                                                                    newlin)
                        outfile.write(line)
                for index, row in df_future.iterrows():
                        line = '{} {:>3} {:>3}  0 0 0  {:>5.4f}  {:>5.4f}'.format(row['year'], row['month'], row['day'],
                                                                                  row[pr01], row[pr02])
                        line += '  {:>8.4f}  {:>8.4f}  {:>8.4f}  {:>8.4f}{}'.format(row[tmax01], row[tmax02],
                                                                                    row[tmin01], row[tmin02], newlin)
                        outfile.write(line)

                outfile.close()
print('done.')
